### ISSUE TITLE
CalTRACK Issue: Improved handling of "Bad Buildings"

### ISSUE THREAD

**Issue by steevschmidt** [energy-market-methods/caltrack#123]
### Prerequisites

* [x] Are you opening this issue in the correct repository (caltrack/grid/seat)?
* [x] Did you perform a search of previous Github issues to check if this issue has been previously considered?

**Article reference number in CalTRACK documentation (optional):** 
1.4.5 or perhaps a new section (?)
(Also, see related issue #103, closed during CalTRACK transition from OEE to EM2.)

### Description

**Background**: Current NMEC methods have a known weakness: they don't do well for buildings with unpredictable energy use. This was noted in the seminal paper on "Automated measurement and verification: Performance of public domain whole-building electric baseline models" (Granderson, et al., 2015) in several passages including:

> The median absolute bias is between 4.5% and 4.8% for all of the models, and the mean is between 8.3% and 8.5% (see Table 1). There are a few buildings for which the predictions are extremely poor, **with errors greater than 75%** (in either direction)...

[Emphasis added], and

> ...errors in whole-building measurement and verification are due to the robustness of the baseline model _in combination with_ the predictability of the building...

[Emphasis by original authors].

This issue was also highlighted in [this analysis by kW engineering](http://www.kw-engineering.com/nmec-normalized-metered-energy-consumption/), when describing NMEC applicability to a "Bad Building":
> Not All Buildings Work
> The best application of whole building methods is for “predictable” buildings and systems. Predictable means an accurate energy model can be developed for a building’s energy use.

HEA has been working with "high energy homes" since 2010, and concluded that many of these homes are "Bad Buildings": their energy use is unique and often varies from month to month and year to year due to a wide range of issues including thermostat wars, seasonal HVAC settings, windows left open, pet requirements, vacations, visiting in-laws, changing occupancy hours, variations in behavioral energy use, new or replaced plug loads, etc, etc. The first cohort of 80 of these homes analyzed using CalTRACK v1 methods in March 2018 resulted in average CVRMSE of 29% for electricity and 56% for natural gas, both well above the ASHRAE limit of 25%, demonstrating "bad predictability".

During CalTRACK phase 2 we agreed we don't want to automatically disqualify these "bad buildings" from P4P programs due to bad model fit (see discussion & examples in #71). However, perhaps we can improve the methods to handle these buildings better.

**Issue**:  CalTRACK methods currently depend on an energy model derived from the baseline period, and then applied to the weather from the reporting period, as shown in this OEE diagram:
  ![OEE](https://user-images.githubusercontent.com/36048787/57559390-687d9680-7336-11e9-9dbc-60daffb6e694.png)

Summarizing the basic steps of the existing CalTRACK methods:
1. Use building energy and weather data from the baseline period to construct a model;
2. Use that model with the weather from the reporting period to create the counterfactual, predicting the reporting period energy consumption;
3. Calculate the difference between predicted and actual energy use in the reporting period to identify the energy savings.
But as described above some buildings are **not predictable**, so step 2 introduces significant errors to the savings calculation. This issue suggests an alternative approach for these buildings.

**Requested CalTRACK changes**: Since 2014 HEA has used a different approach to measure savings on these "bad buildings". The primary difference is that we do not build a model to predict energy use; instead, we build a model to disaggregate the dependent loads (heating and cooling) during the baseline period, then build another model for the reporting period to do the same, then compare the [weather-normalized] loads directly.

For example: The two energy profiles below present the disaggregated energy loads of the same SF Bay Area home over two different periods.

![PP08816](https://user-images.githubusercontent.com/36048787/57560339-d330d100-733a-11e9-8d9d-f43d09cae6b9.jpg)
The vertical axis of the charts show monthly utility bill totals (in dollars), including both electricity and natural gas. The "Winter Heating" load was derived using a regression of meter and weather data for each period, resulting in two different "models", perhaps with different balance point temperatures. The other loads displayed above are independent of weather -- combined they represent the "y-intercept" in simpler models. Note: these charts show dollars, but the same disaggregated load information is available in kWh (for the electric component) and therms (for natural gas).

Our energy savings calculation for this home "normalizes" only the heating load:
> [Baseline Period Heating Load] * 2083/2396 = [Expected Reported Period Heating]
> [Expected Reported Period Heating] - [Actual Reporting Period Heating] = [Heating Savings]
> [Baseline Period Other Loads] - [Reporting Period Other Loads] = [Other Savings]
> [Total Savings (AUE)] = [Heating Savings] + [Other Savings]

This method still utilizes building energy models to identify weather-dependent loads, but it does not use those models to predict future energy use... a major benefit when analyzing buildings that are inherently unpredictable.

### Proposed test methodology

1. Identify a test sample of appropriate "bad buildings" with poor CVRMSE values using existing methods.
2. Record both CVRMSE values and Avoided Energy Use for these homes individually and in aggregate.
3. Adjust methods in a manner similar to that described above, or something better.
4. Rerun with the updated methods, and compare "after" CVRMSE and AEU values.

### Acceptance Criteria

CVRMSE values should improve in most cases, and never get worse.

**Comment by steevschmidt** [comment]
Notes from working group meeting on 10/23/19:
 * Ethan raised questions about the "counterfactual" in this approach. Steve responded that no model is used to **predict** reporting period energy use: instead, the data in the reporting period is used to develop a new model disaggregating heating & cooling loads, and that model can have different parameters (e.g. balance point temp) than the baseline model. The goal is an accurate assessment of the loads that are to be normalized (via a linear relationship with DDs) in each period. Current CalTRACK methods produce a single model for the baseline period, and apply that same model to the reporting period.
 * Caroline raised questions about whether behavioral changes (such as a change to a thermostat set point, which will change the balance point temp) should be taken into account when calculating CalTRACK savings. Steve believes yes, all changes should be included in metered savings.

[I took poor notes, so I hope other attendees will correct/enhance my descriptions above.]

**Comment by danrubado** [comment]
I don't understand how the proposal addresses the issue that was described. How would savings be calculated in these cases?  As Ethan pointed out, what IS the counterfactual here?

**Comment by steevschmidt** [comment]
As a result of several offline discussions I now understand the approach described above in fact uses the same Counterfactual as CalTRACK: a simple linear relationship between heating and cooling loads and degree days. The primary benefit of the approach described is not more accurate savings, but the attribution of savings to specific load categories (heating, cooling, base). And while this is critical for HEA's service, it is not part of CalTRACK.

So upon further consideration HEA would like to remove this issue from consideration; we believe issues #122 and #129 are more critical to improve handling of "bad buildings".
