### ISSUE TITLE
Prioritization for Sprint #1, May 2019

### ISSUE THREAD

**Issue by jkoliner** [energy-market-methods/caltrack#131]
## CalTRACK Prioritization
This is the official thread for voting on Round 1 of the 2019 CalTRACK Prioritization slate. First, here are the relevant issues:

[#117: Monthly Fixed Effects](https://github.com/energy-market-methods/caltrack/issues/117) - Use monthly fixed effects to control for seasonal variation instead of monthly WLS regressions.
[#118: Interpolation of integral therms for daily data](https://github.com/energy-market-methods/caltrack/issues/118)
[#120: Calculate Degree Days using Degree Hours when available](https://github.com/energy-market-methods/caltrack/issues/120)
[#121: Heating balance point temperatures abnormally low?](https://github.com/energy-market-methods/caltrack/issues/121) - Investigate methods for determining building balance point besides grid search/R^2.
[#122: Enhance Testing Methods](https://github.com/energy-market-methods/caltrack/issues/122) - Develop a CalTRACK testing methodology and public data repository for benchmarking versions.
[#123: Improved handling of "Bad Buildings"](https://github.com/energy-market-methods/caltrack/issues/123) - Use successive disaggregation and model both pre and post period energy use
[#124: Improve handling of buildings with weather-energy misalignments](https://github.com/energy-market-methods/caltrack/issues/124) - Incorporate lagged weather variables into daily models
[#125: Ensure that AEU includes all days in reporting period](https://github.com/energy-market-methods/caltrack/issues/125) - Change handling of missing weather data to include more days in the reporting period.
[#126: Baseline data procedure for billing data](https://github.com/energy-market-methods/caltrack/issues/126) - Tighten specification of baseline period.
[#127: Improve stability of incremental savings via rolling 12 month reporting periods](https://github.com/energy-market-methods/caltrack/issues/127)
[#128: Non-res vs. res models](https://github.com/energy-market-methods/caltrack/issues/128) - Use an alternative specification or specifications for non-residential hourly models.
[#129: Vote on/agree to a uniform testing approach](https://github.com/energy-market-methods/caltrack/issues/129) -Initiate a process to determine a uniform test methodology for CalTRACK.
[#130: "Month type" or "week type" control to address intercept-only model issues with more frequent payments](https://github.com/energy-market-methods/caltrack/issues/130)

## How to Vote
First, write out your name and the organization you are representing. Then, please rank each issue with a value from __1__ (_most important_) to __5__ (_least important_), according to its urgency and potential impact. Leave your votes as comments on this issue (not the linked issues), with all votes listed in the order the issues are presented above. If you do not feel qualified to vote on a given issue in the list, please include its number but place a dash (-) next to it, so we know that you didn't skip over it accidentally. Once voting is closed, issues will be arranged in prioritization by average rank (excluding opt-outs).

Member organizations receive one vote per organization, per issue. Please ensure that only one person from your organization comments. If multiple comments come from the same organization, we will take only the votes from the first comment.

Voting will remain open __until 11:59 PM Pacific, on Tuesday, June 4th__.

## Example
This is an example of how to present your votes in your comment (_these are not my actual votes_).

Jon Koliner, Apex Analytics
#117: 3
#118: 3
#120: -
#121: 1
#122: 5
#123: -
#124: -
#125: 5
#126: 4
#127: 3
#128: 2
#129: 1
#130: 1

**Comment by DrDAJump** [comment]
David Jump, kW Engineering
#117: 1
#118: 4
#120: -
#121: 3
#122: -
#123: -
#124: -
#125: 5
#126: -
#127: -
#128: 2
#129: 1
#130: -

**Comment by hshaban** [comment]
Hassan Shaban, Recurve
#117: 2
#118: 1
#120: 1
#121: 4
#122: 3
#123: 5
#124: 3
#125: 5
#126: 1
#127: 3
#128: 4
#129: 3
#130: 2

**Comment by james-russell** [comment]
James Russell, CLEAResult
#117: 1
#118: 1
#120: 2
#121: 4
#122: 3
#123: 4
#124: 3
#125: -
#126: 2
#127: 3
#128: 1
#129: -
#130: 5

**Comment by MLGuilfoyle** [comment]
Mindy Guilfoyle, Franklin Energy
#117: 3
#118: 4
#120: 1
#121: 4
#122: 5
#123: 2
#124: 3
#125: 1
#126: 5
#127: 1
#128: 2
#129: 3
#130: 2

**Comment by CraigPTO** [comment]
Craig Sinnamon, Power TakeOff
#117: 3
#118: 3
#120: 1
#121: 1
#122: 3
#123: 1
#124: 1
#125: 5
#126: 5
#127: 1
#128: 3
#129: 5
#130: 5

**Comment by KMonsees-NYSERDA** [comment]
Kyle Monsees, NYSERDA
#117: 2
#118: 2
#120: 1
#121: 4
#122: 3
#123: 4
#124: 3
#125: 5
#126: 2
#127: 1
#128: 4
#129: 3 
#130: 1

**Comment by AndrewYRoyal** [comment]
Andrew Royal, Res-Intel
#117: 1
#118: -
#120: -
#121: 2
#122: 3
#123: 4
#124: 5
#125: 1
#126: 2
#127: -
#128: 1
#129: 1
#130: 2

**Comment by lwebster101** [comment]
Lia Webster, Facility Energy Solutions on behalf of EVO
--
#117: | 1
#118: | -
#120: | 3
#121: | 2
#122: | 2
#123: | -
#124: | -
#125: | -
#126: | 2
#127:   - | -
#128: | 1
#129: | 1
#130: | -

**Comment by yroussev** [comment]
Yassen Roussev, Frontier Energy
#117: 1 
#118: 2
#120: 2
#121: 3
#122: 2
#123: 3
#124: 3
#125: 3
#126: 1
#127: 3
#128: 1
#129: -
#130: 2

**Comment by jkoliner** [comment]
Jon Koliner, Apex Analytics
#117: 1
#118: 2
#120: 2
#121: 2
#122: 3
#123: 2
#124: 4
#125: 2
#126: 1
#127: 5
#128: 1
#129: 1
#130: 2

**Comment by carolinemfrancispge** [comment]
Caroline Massad Francis, PG&E

#117: 1
#118: 2
#120: 3
#121: -
#122: -
#123: 5
#124: -
#125: -
#126: 1
#127: 5
#128: 1
#129: 1
#130: 3

**Comment by qvallery** [comment]
Quashaun Vallery, MCE
#117: 1
#118: 3
#120: 3
#121: 2
#122: 4
#123: 4
#124: -
#125: 5
#126: 2
#127: 4
#128: 2
#129: 4
#130: 1

**Comment by steevschmidt** [comment]
Steve Schmidt, Home Energy Analytics:
#117: 2
#118: 1
#120: 1
#121: 1
#122: 1
#123: 1
#124: 1
#125: 1
#126: 5
#127: 1
#128: 5
#129: 1
#130: 4

**Comment by lwebster101** [comment]
Hi Jon-
I posted my priorities but did not receive an email.

Thank you,
Lia Webster

720.470.9297

 Please excuse any typos.

On Jun 4, 2019, at 4:43 PM, Jon Koliner <notifications@github.com<mailto:notifications@github.com>> wrote:


Jon Koliner, Apex Analytics
#117<https://github.com/energy-market-methods/caltrack/issues/117>: 1
#118<https://github.com/energy-market-methods/caltrack/issues/118>: 2
#120<https://github.com/energy-market-methods/caltrack/issues/120>: 2
#121<https://github.com/energy-market-methods/caltrack/issues/121>: 2
#122<https://github.com/energy-market-methods/caltrack/issues/122>: 3
#123<https://github.com/energy-market-methods/caltrack/issues/123>: 2
#124<https://github.com/energy-market-methods/caltrack/issues/124>: 4
#125<https://github.com/energy-market-methods/caltrack/issues/125>: 2
#126<https://github.com/energy-market-methods/caltrack/issues/126>: 1
#127<https://github.com/energy-market-methods/caltrack/issues/127>: 5
#128<https://github.com/energy-market-methods/caltrack/issues/128>: 1
#129<https://github.com/energy-market-methods/caltrack/issues/129>: 1
#130<https://github.com/energy-market-methods/caltrack/issues/130>: 2

**Comment by jkoliner** [comment]
Here are the tallied results:

#117: 1.54
#120: 1.82
#128: 2.15
#129: 2.18
#118: 2.27
#126: 2.42
#130: 2.64
#121: 2.67
#127: 2.70
#124: 2.89
#122: 2.91
#123: 3.18
#125: 3.30

The averaging spreadsheet can be found here: [Prioritization for Sprint #1](https://docs.google.com/spreadsheets/d/1kjqRSA8fHnyVOtdUqQ5UxQ6K-cikUrfJMOgF_T3B-oE/edit?usp=sharing)
